### ISSUE TITLE
스키마 수정 필요할수도?

### ISSUE THREAD

**Issue by LEEGURTS** [KW-FINDVIBE/FINDVIBE#3]
![image](https://user-images.githubusercontent.com/79559361/231453510-25acf74d-c707-4298-9972-3b8540d8b662.png)
![image](https://user-images.githubusercontent.com/79559361/231453916-f883cfac-0744-4c7e-8d57-ab1d1b73da10.png)

지금 현재 프로그램 형태가 예상되는 랜드마크(타켓) 과 예상되는 촬영위치(포지션리스트) 로 구성되어야할 거 같으므로 res의 형태가 바뀌어야할거같음.

**Comment by HungKungE** [comment]
어차피 파이썬 서버에서 결과를 json으로 전송하고, DB에도 json을 string으로 저장할 거라서 상관 없음.
client에서만 제대로 처리해주면 될 듯.

**Comment by HungKungE** [comment]
client는 너가 주석한 대로 바꾸면 될듯?
